### ISSUE TITLE
doesnt open

### ISSUE THREAD

**Issue by LuigiMario1** [sudo-000/Minecraft-Developer-Edition#1]

**Comment by LuigiMario1** [comment]
also missing a ton of dlls

**Comment by happymimimix** [comment]
How did you open it? From start menu or double click the exe file?

**Comment by happymimimix** [comment]
Minecraft is a UWP app, double clicking the exe file does nothing.

**Comment by happymimimix** [comment]
Make sure you are on windows 10 1709 or above, and make sure you have developer mode turned on. 
And please first make sure you can play the commercial version normally before trying out this internal beta. 
You can get a trial version of Minecraft UWP from Microsoft Store. 
If that one works fine, uninstall first, then make sure you turned on developer mode, then install this internal beta.

**Comment by LuigiMario1** [comment]
> How did you open it? From start menu or double click the exe file?

double click

**Comment by happymimimix** [comment]
> > How did you open it? From start menu or double click the exe file?
> 
> double click

I know why.

**Comment by happymimimix** [comment]
> Minecraft is a UWP app, double clicking the exe file does nothing.

Double click the exe file does not work.

**Comment by happymimimix** [comment]
Have you read the terms and conditions in the installer? 

> > How did you open it? From start menu or double click the exe file?
> 
> double click

**Comment by LuigiMario1** [comment]
> Have you read the terms and conditions in the installer?
> 
> > > How did you open it? From start menu or double click the exe file?
> > 
> > 
> > double click

bro who reads terms and conditions these days

**Comment by happymimimix** [comment]
> > Have you read the terms and conditions in the installer?
> > > > How did you open it? From start menu or double click the exe file?
> > > 
> > > 
> > > double click
> 
> bro who reads terms and conditions these days

I put instructions on how to install inside, please read. 
It says terms and conditions in the installer, but it's not in fact. 

Maybe I should change the text to say something like: Instructions, or Readme? 
Honestly, not even myself want to read those things. 

Have a look at that see if that solves your problem.

**Comment by LuigiMario1** [comment]
i pinned to start menu and tried to run it but it didint work

**Comment by LuigiMario1** [comment]
i read the instructions and theres nothing useful in there

**Comment by happymimimix** [comment]
> i pinned to start menu and tried to run it but it didint work

Manually pin doesn't work! 
Again, minecraft is a UWP app, it's very different from normal windows programs. 
Go read the term and conditions in the installer, I put instructions about how to install inside.

**Comment by LuigiMario1** [comment]
i read it

**Comment by happymimimix** [comment]
1. Please make sure your device can play the public commercial version of minecraft normally before trying out this internal developer edition! 
2. If you have minecraft UWP installed already, please uninstall first before continue. 
3. Developer mode must be turned on on your device to be able to install this package successfully. 
To turn on developer mode, go to Settings -> Update and Security -> For Developers -> Developer Mode

You sure you've already done these steps?

**Comment by happymimimix** [comment]
Download a free trial of the commercial minecraft here: 
https://apps.microsoft.com/store/detail/minecraft-for-windows/9NBLGGH2JHXJ

Make sure that this one runs on your device normally before continuing.

**Comment by LuigiMario1** [comment]
> 1. Please make sure your device can play the public commercial version of minecraft normally before trying out this internal developer edition!
> 2. If you have minecraft UWP installed already, please uninstall first before continue.
> 3. Developer mode must be turned on on your device to be able to install this package successfully.
>    To turn on developer mode, go to Settings -> Update and Security -> For Developers -> Developer Mode
> 
> You sure you've already done these steps?

i can play public versions
i uninstalled bedrock edition
dev mode is on

**Comment by happymimimix** [comment]
> > 1. Please make sure your device can play the public commercial version of minecraft normally before trying out this internal developer edition!
> > 2. If you have minecraft UWP installed already, please uninstall first before continue.
> > 3. Developer mode must be turned on on your device to be able to install this package successfully.
> >    To turn on developer mode, go to Settings -> Update and Security -> For Developers -> Developer Mode
> > 
> > You sure you've already done these steps?
> 
> i can play public versions i uninstalled bedrock edition dev mode is on

Now, try uninstall and reinstall this internal beta.

**Comment by LuigiMario1** [comment]
now it says its missing a ton of dlls

**Comment by happymimimix** [comment]
Shift + RightClick in the installation directory and click open command prompt
then type the following command inside: 
powershell Add-Appxpackage -Register %~dp0AppxManifest.xml

Copy the output and send it to me.

**Comment by happymimimix** [comment]
Probably a 5 second delay it still too short, 
and then the bat file just self deletes. 
I should change that later to let debugging become more friendly.

**Comment by LuigiMario1** [comment]
> Shift + RightClick in the installation directory and click open command prompt then type the following command inside: powershell Add-Appxpackage -Register %~dp0AppxManifest.xml
> 
> Copy the output and send it to me.

there is no open in commandprompt

**Comment by happymimimix** [comment]
Is there a open powershell? 
If yes, click that and type cmd inside. 
Then paste the commands above.

**Comment by happymimimix** [comment]
> > Shift + RightClick in the installation directory and click open command prompt then type the following command inside: powershell Add-Appxpackage -Register %~dp0AppxManifest.xml
> > Copy the output and send it to me.
> 
> there is no open in commandprompt

Make sure you hold the Shift key when right clicking on blank areas in the folder

**Comment by LuigiMario1** [comment]
> 

Add-Appxpackage : Cannot find path 'C:\Minecraft-DEV\%~dp0AppxManifest.xml' because it does not exist.
At line:1 char:1
+ Add-Appxpackage -Register %~dp0AppxManifest.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Minecraft-DEV\%~dp0AppxManifest.xml:String) [Add-AppxPackage], ItemN
   otFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

**Comment by happymimimix** [comment]
> 

Humm...
Try again with powershell Add-Appxpackage -Register .\AppxManifest.xml

**Comment by happymimimix** [comment]
See if that works. 

> > 
> 
> Humm... Try again with powershell Add-Appxpackage -Register .\AppxManifest.xml

**Comment by happymimimix** [comment]
> > 
> 
> Humm... Try again with powershell Add-Appxpackage -Register .\AppxManifest.xml

If this gives you no error message, that means you are ready to go! 
Open start menu and click all apps, you will find minecraft.

**Comment by LuigiMario1** [comment]
how do i know its dev

**Comment by LuigiMario1** [comment]
IT WORKS

**Comment by happymimimix** [comment]
> how do i know its dev

Go to settings and you will see these crazy options: 
![image](https://github.com/sudo-000/Minecraft-Developer-Edition/assets/107282563/6c401447-b71e-4fc4-b5a4-387d7f8d06d1)

**Comment by happymimimix** [comment]
Honestly, I think I should re-design the installer a bit to make it more friendly.

**Comment by happymimimix** [comment]
Please wait for the next update : )
